package model

import "time"

type Event struct {
	Action       string `json:"action"`
	Installation struct {
		ID      int `json:"id"`
		Account struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"account"`
		RepositorySelection string `json:"repository_selection"`
		AccessTokensURL     string `json:"access_tokens_url"`
		RepositoriesURL     string `json:"repositories_url"`
		HTMLURL             string `json:"html_url"`
		AppID               int    `json:"app_id"`
		TargetID            int    `json:"target_id"`
		TargetType          string `json:"target_type"`
		Permissions         struct {
			Metadata            string `json:"metadata"`
			Contents            string `json:"contents"`
			Issues              string `json:"issues"`
			Administration      string `json:"administration"`
			Statuses            string `json:"statuses"`
			RepositoryProjects  string `json:"repository_projects"`
			RepositoryHooks     string `json:"repository_hooks"`
			PullRequests        string `json:"pull_requests"`
			Pages               string `json:"pages"`
			Deployments         string `json:"deployments"`
			Checks              string `json:"checks"`
			VulnerabilityAlerts string `json:"vulnerability_alerts"`
		} `json:"permissions"`
		Events         []string `json:"events"`
		CreatedAt      int      `json:"created_at"`
		UpdatedAt      int      `json:"updated_at"`
		SingleFileName string   `json:"single_file_name"`
		NodeID         string   `json:"node_id"`
	} `json:"installation"`
	Repositories []struct {
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		Name     string `json:"name"`
		FullName string `json:"full_name"`
		Private  bool   `json:"private"`
	} `json:"repositories"`
	Sender struct {
		Login             string `json:"login"`
		ID                int    `json:"id"`
		NodeID            string `json:"node_id"`
		AvatarURL         string `json:"avatar_url"`
		GravatarID        string `json:"gravatar_id"`
		URL               string `json:"url"`
		HTMLURL           string `json:"html_url"`
		FollowersURL      string `json:"followers_url"`
		FollowingURL      string `json:"following_url"`
		GistsURL          string `json:"gists_url"`
		StarredURL        string `json:"starred_url"`
		SubscriptionsURL  string `json:"subscriptions_url"`
		OrganizationsURL  string `json:"organizations_url"`
		ReposURL          string `json:"repos_url"`
		EventsURL         string `json:"events_url"`
		ReceivedEventsURL string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
		Email             string `json:"email"`
	} `json:"sender"`
	Alert struct {
		Number     int         `json:"number"`
		SecretType string      `json:"secret_type"`
		Resolution interface{} `json:"resolution"`
		ResolvedBy interface{} `json:"resolved_by"`
		ResolvedAt interface{} `json:"resolved_at"`
		CreatedAt  time.Time   `json:"created_at"`
		URL        string      `json:"url"`
		HTMLURL    string      `json:"html_url"`
		Instances  []struct {
			Ref         string `json:"ref"`
			AnalysisKey string `json:"analysis_key"`
			Environment string `json:"environment"`
			State       string `json:"state"`
		} `json:"instances"`
		State           string      `json:"state"`
		DismissedBy     interface{} `json:"dismissed_by"`
		DismissedAt     interface{} `json:"dismissed_at"`
		DismissedReason interface{} `json:"dismissed_reason"`
		Rule            struct {
			ID          string `json:"id"`
			Severity    string `json:"severity"`
			Description string `json:"description"`
		} `json:"rule"`
		Tool struct {
			Name    string      `json:"name"`
			Version interface{} `json:"version"`
		} `json:"tool"`
		ID                  int    `json:"id"`
		AffectedRange       string `json:"affected_range"`
		AffectedPackageName string `json:"affected_package_name"`
		FixedIn             string `json:"fixed_in"`
		ExternalReference   string `json:"external_reference"`
		ExternalIdentifier  string `json:"external_identifier"`
		Severity            string `json:"severity"`
		GhsaID              string `json:"ghsa_id"`
	} `json:"alert"`
	Repository struct {
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		Name     string `json:"name"`
		FullName string `json:"full_name"`
		Private  bool   `json:"private"`
		Owner    struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
			Name              string `json:"name"`
			Email             string `json:"email"`
		} `json:"owner"`
		HTMLURL          string      `json:"html_url"`
		Description      string      `json:"description"`
		Fork             bool        `json:"fork"`
		URL              string      `json:"url"`
		ForksURL         string      `json:"forks_url"`
		KeysURL          string      `json:"keys_url"`
		CollaboratorsURL string      `json:"collaborators_url"`
		TeamsURL         string      `json:"teams_url"`
		HooksURL         string      `json:"hooks_url"`
		IssueEventsURL   string      `json:"issue_events_url"`
		EventsURL        string      `json:"events_url"`
		AssigneesURL     string      `json:"assignees_url"`
		BranchesURL      string      `json:"branches_url"`
		TagsURL          string      `json:"tags_url"`
		BlobsURL         string      `json:"blobs_url"`
		GitTagsURL       string      `json:"git_tags_url"`
		GitRefsURL       string      `json:"git_refs_url"`
		TreesURL         string      `json:"trees_url"`
		StatusesURL      string      `json:"statuses_url"`
		LanguagesURL     string      `json:"languages_url"`
		StargazersURL    string      `json:"stargazers_url"`
		ContributorsURL  string      `json:"contributors_url"`
		SubscribersURL   string      `json:"subscribers_url"`
		SubscriptionURL  string      `json:"subscription_url"`
		CommitsURL       string      `json:"commits_url"`
		GitCommitsURL    string      `json:"git_commits_url"`
		CommentsURL      string      `json:"comments_url"`
		IssueCommentURL  string      `json:"issue_comment_url"`
		ContentsURL      string      `json:"contents_url"`
		CompareURL       string      `json:"compare_url"`
		MergesURL        string      `json:"merges_url"`
		ArchiveURL       string      `json:"archive_url"`
		DownloadsURL     string      `json:"downloads_url"`
		IssuesURL        string      `json:"issues_url"`
		PullsURL         string      `json:"pulls_url"`
		MilestonesURL    string      `json:"milestones_url"`
		NotificationsURL string      `json:"notifications_url"`
		LabelsURL        string      `json:"labels_url"`
		ReleasesURL      string      `json:"releases_url"`
		DeploymentsURL   string      `json:"deployments_url"`
		CreatedAt        time.Time   `json:"created_at"`
		UpdatedAt        time.Time   `json:"updated_at"`
		PushedAt         time.Time   `json:"pushed_at"`
		GitURL           string      `json:"git_url"`
		SSHURL           string      `json:"ssh_url"`
		CloneURL         string      `json:"clone_url"`
		SvnURL           string      `json:"svn_url"`
		Homepage         string      `json:"homepage"`
		Size             int         `json:"size"`
		StargazersCount  int         `json:"stargazers_count"`
		WatchersCount    int         `json:"watchers_count"`
		Language         string      `json:"language"`
		HasIssues        bool        `json:"has_issues"`
		HasProjects      bool        `json:"has_projects"`
		HasDownloads     bool        `json:"has_downloads"`
		HasWiki          bool        `json:"has_wiki"`
		HasPages         bool        `json:"has_pages"`
		ForksCount       int         `json:"forks_count"`
		MirrorURL        interface{} `json:"mirror_url"`
		Archived         bool        `json:"archived"`
		Disabled         bool        `json:"disabled"`
		OpenIssuesCount  int         `json:"open_issues_count"`
		License          interface{} `json:"license"`
		Forks            int         `json:"forks"`
		OpenIssues       int         `json:"open_issues"`
		Watchers         int         `json:"watchers"`
		DefaultBranch    string      `json:"default_branch"`
		Stargazers       int         `json:"stargazers"`
		MasterBranch     string      `json:"master_branch"`
		Permissions      struct {
			Pull  bool `json:"pull"`
			Push  bool `json:"push"`
			Admin bool `json:"admin"`
		} `json:"permissions"`
	} `json:"repository"`
	Organization struct {
		Login            string `json:"login"`
		ID               int    `json:"id"`
		NodeID           string `json:"node_id"`
		URL              string `json:"url"`
		ReposURL         string `json:"repos_url"`
		EventsURL        string `json:"events_url"`
		HooksURL         string `json:"hooks_url"`
		IssuesURL        string `json:"issues_url"`
		MembersURL       string `json:"members_url"`
		PublicMembersURL string `json:"public_members_url"`
		AvatarURL        string `json:"avatar_url"`
		Description      string `json:"description"`
	} `json:"organization"`
	CheckRun struct {
		ID          int         `json:"id"`
		NodeID      string      `json:"node_id"`
		HeadSha     string      `json:"head_sha"`
		ExternalID  string      `json:"external_id"`
		URL         string      `json:"url"`
		HTMLURL     string      `json:"html_url"`
		DetailsURL  string      `json:"details_url"`
		Status      string      `json:"status"`
		Conclusion  interface{} `json:"conclusion"`
		StartedAt   time.Time   `json:"started_at"`
		CompletedAt interface{} `json:"completed_at"`
		Output      struct {
			Title            interface{} `json:"title"`
			Summary          interface{} `json:"summary"`
			Text             interface{} `json:"text"`
			AnnotationsCount int         `json:"annotations_count"`
			AnnotationsURL   string      `json:"annotations_url"`
		} `json:"output"`
		Name       string `json:"name"`
		CheckSuite struct {
			ID           int         `json:"id"`
			NodeID       string      `json:"node_id"`
			HeadBranch   string      `json:"head_branch"`
			HeadSha      string      `json:"head_sha"`
			Status       string      `json:"status"`
			Conclusion   interface{} `json:"conclusion"`
			URL          string      `json:"url"`
			Before       string      `json:"before"`
			After        string      `json:"after"`
			PullRequests []struct {
				URL    string `json:"url"`
				ID     int    `json:"id"`
				Number int    `json:"number"`
				Head   struct {
					Ref  string `json:"ref"`
					Sha  string `json:"sha"`
					Repo struct {
						ID   int    `json:"id"`
						URL  string `json:"url"`
						Name string `json:"name"`
					} `json:"repo"`
				} `json:"head"`
				Base struct {
					Ref  string `json:"ref"`
					Sha  string `json:"sha"`
					Repo struct {
						ID   int    `json:"id"`
						URL  string `json:"url"`
						Name string `json:"name"`
					} `json:"repo"`
				} `json:"base"`
			} `json:"pull_requests"`
			App       App       `json:"app"`
			CreatedAt time.Time `json:"created_at"`
			UpdatedAt time.Time `json:"updated_at"`
		} `json:"check_suite"`
		App          App `json:"app"`
		PullRequests []struct {
			URL    string `json:"url"`
			ID     int    `json:"id"`
			Number int    `json:"number"`
			Head   struct {
				Ref  string `json:"ref"`
				Sha  string `json:"sha"`
				Repo struct {
					ID   int    `json:"id"`
					URL  string `json:"url"`
					Name string `json:"name"`
				} `json:"repo"`
			} `json:"head"`
			Base struct {
				Ref  string `json:"ref"`
				Sha  string `json:"sha"`
				Repo struct {
					ID   int    `json:"id"`
					URL  string `json:"url"`
					Name string `json:"name"`
				} `json:"repo"`
			} `json:"base"`
		} `json:"pull_requests"`
		Deployment struct {
			URL                 string      `json:"url"`
			ID                  int         `json:"id"`
			NodeID              string      `json:"node_id"`
			Task                string      `json:"task"`
			OriginalEnvironment string      `json:"original_environment"`
			Environment         string      `json:"environment"`
			Description         interface{} `json:"description"`
			CreatedAt           time.Time   `json:"created_at"`
			UpdatedAt           time.Time   `json:"updated_at"`
			StatusesURL         string      `json:"statuses_url"`
			RepositoryURL       string      `json:"repository_url"`
		} `json:"deployment"`
	} `json:"check_run"`
	ProjectColumn struct {
		URL        string    `json:"url"`
		ProjectURL string    `json:"project_url"`
		CardsURL   string    `json:"cards_url"`
		ID         int       `json:"id"`
		NodeID     string    `json:"node_id"`
		Name       string    `json:"name"`
		CreatedAt  time.Time `json:"created_at"`
		UpdatedAt  time.Time `json:"updated_at"`
	} `json:"project_column"`
	HookID int `json:"hook_id"`
	Hook   struct {
		Type   string   `json:"type"`
		ID     int      `json:"id"`
		Name   string   `json:"name"`
		Active bool     `json:"active"`
		Events []string `json:"events"`
		Config struct {
			ContentType string `json:"content_type"`
			InsecureSsl string `json:"insecure_ssl"`
			URL         string `json:"url"`
		} `json:"config"`
		UpdatedAt    time.Time `json:"updated_at"`
		CreatedAt    time.Time `json:"created_at"`
		URL          string    `json:"url"`
		TestURL      string    `json:"test_url"`
		PingURL      string    `json:"ping_url"`
		LastResponse struct {
			Code    interface{} `json:"code"`
			Status  string      `json:"status"`
			Message interface{} `json:"message"`
		} `json:"last_response"`
	} `json:"hook"`
	Comment struct {
		URL     string `json:"url"`
		HTMLURL string `json:"html_url"`
		ID      int    `json:"id"`
		NodeID  string `json:"node_id"`
		User    struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"user"`
		Position            int         `json:"position"`
		Line                interface{} `json:"line"`
		Path                string      `json:"path"`
		CommitID            string      `json:"commit_id"`
		CreatedAt           time.Time   `json:"created_at"`
		UpdatedAt           time.Time   `json:"updated_at"`
		AuthorAssociation   string      `json:"author_association"`
		Body                string      `json:"body"`
		PullRequestReviewID int         `json:"pull_request_review_id"`
		DiffHunk            string      `json:"diff_hunk"`
		OriginalPosition    int         `json:"original_position"`
		OriginalCommitID    string      `json:"original_commit_id"`
		PullRequestURL      string      `json:"pull_request_url"`
		Links               struct {
			Self struct {
				Href string `json:"href"`
			} `json:"self"`
			HTML struct {
				Href string `json:"href"`
			} `json:"html"`
			PullRequest struct {
				Href string `json:"href"`
			} `json:"pull_request"`
		} `json:"_links"`
		ParentID          interface{} `json:"parent_id"`
		ChildCommentCount int         `json:"child_comment_count"`
		RepositoryURL     string      `json:"repository_url"`
		DiscussionID      int         `json:"discussion_id"`
		IssueURL          string      `json:"issue_url"`
	} `json:"comment"`
	CheckSuite struct {
		ID           int    `json:"id"`
		NodeID       string `json:"node_id"`
		HeadBranch   string `json:"head_branch"`
		HeadSha      string `json:"head_sha"`
		Status       string `json:"status"`
		Conclusion   string `json:"conclusion"`
		URL          string `json:"url"`
		Before       string `json:"before"`
		After        string `json:"after"`
		PullRequests []struct {
			URL    string `json:"url"`
			ID     int    `json:"id"`
			Number int    `json:"number"`
			Head   struct {
				Ref  string `json:"ref"`
				Sha  string `json:"sha"`
				Repo struct {
					ID   int    `json:"id"`
					URL  string `json:"url"`
					Name string `json:"name"`
				} `json:"repo"`
			} `json:"head"`
			Base struct {
				Ref  string `json:"ref"`
				Sha  string `json:"sha"`
				Repo struct {
					ID   int    `json:"id"`
					URL  string `json:"url"`
					Name string `json:"name"`
				} `json:"repo"`
			} `json:"base"`
		} `json:"pull_requests"`
		App                  App       `json:"app"`
		CreatedAt            time.Time `json:"created_at"`
		UpdatedAt            time.Time `json:"updated_at"`
		LatestCheckRunsCount int       `json:"latest_check_runs_count"`
		CheckRunsURL         string    `json:"check_runs_url"`
		HeadCommit           struct {
			ID        string    `json:"id"`
			TreeID    string    `json:"tree_id"`
			Message   string    `json:"message"`
			Timestamp time.Time `json:"timestamp"`
			Author    struct {
				Name  string `json:"name"`
				Email string `json:"email"`
			} `json:"author"`
			Committer struct {
				Name  string `json:"name"`
				Email string `json:"email"`
			} `json:"committer"`
		} `json:"head_commit"`
	} `json:"check_suite"`
	Forkee struct {
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		Name     string `json:"name"`
		FullName string `json:"full_name"`
		Private  bool   `json:"private"`
		Owner    struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"owner"`
		HTMLURL          string      `json:"html_url"`
		Description      interface{} `json:"description"`
		Fork             bool        `json:"fork"`
		URL              string      `json:"url"`
		ForksURL         string      `json:"forks_url"`
		KeysURL          string      `json:"keys_url"`
		CollaboratorsURL string      `json:"collaborators_url"`
		TeamsURL         string      `json:"teams_url"`
		HooksURL         string      `json:"hooks_url"`
		IssueEventsURL   string      `json:"issue_events_url"`
		EventsURL        string      `json:"events_url"`
		AssigneesURL     string      `json:"assignees_url"`
		BranchesURL      string      `json:"branches_url"`
		TagsURL          string      `json:"tags_url"`
		BlobsURL         string      `json:"blobs_url"`
		GitTagsURL       string      `json:"git_tags_url"`
		GitRefsURL       string      `json:"git_refs_url"`
		TreesURL         string      `json:"trees_url"`
		StatusesURL      string      `json:"statuses_url"`
		LanguagesURL     string      `json:"languages_url"`
		StargazersURL    string      `json:"stargazers_url"`
		ContributorsURL  string      `json:"contributors_url"`
		SubscribersURL   string      `json:"subscribers_url"`
		SubscriptionURL  string      `json:"subscription_url"`
		CommitsURL       string      `json:"commits_url"`
		GitCommitsURL    string      `json:"git_commits_url"`
		CommentsURL      string      `json:"comments_url"`
		IssueCommentURL  string      `json:"issue_comment_url"`
		ContentsURL      string      `json:"contents_url"`
		CompareURL       string      `json:"compare_url"`
		MergesURL        string      `json:"merges_url"`
		ArchiveURL       string      `json:"archive_url"`
		DownloadsURL     string      `json:"downloads_url"`
		IssuesURL        string      `json:"issues_url"`
		PullsURL         string      `json:"pulls_url"`
		MilestonesURL    string      `json:"milestones_url"`
		NotificationsURL string      `json:"notifications_url"`
		LabelsURL        string      `json:"labels_url"`
		ReleasesURL      string      `json:"releases_url"`
		DeploymentsURL   string      `json:"deployments_url"`
		CreatedAt        time.Time   `json:"created_at"`
		UpdatedAt        time.Time   `json:"updated_at"`
		PushedAt         time.Time   `json:"pushed_at"`
		GitURL           string      `json:"git_url"`
		SSHURL           string      `json:"ssh_url"`
		CloneURL         string      `json:"clone_url"`
		SvnURL           string      `json:"svn_url"`
		Homepage         interface{} `json:"homepage"`
		Size             int         `json:"size"`
		StargazersCount  int         `json:"stargazers_count"`
		WatchersCount    int         `json:"watchers_count"`
		Language         interface{} `json:"language"`
		HasIssues        bool        `json:"has_issues"`
		HasProjects      bool        `json:"has_projects"`
		HasDownloads     bool        `json:"has_downloads"`
		HasWiki          bool        `json:"has_wiki"`
		HasPages         bool        `json:"has_pages"`
		ForksCount       int         `json:"forks_count"`
		MirrorURL        interface{} `json:"mirror_url"`
		Archived         bool        `json:"archived"`
		Disabled         bool        `json:"disabled"`
		OpenIssuesCount  int         `json:"open_issues_count"`
		License          interface{} `json:"license"`
		Forks            int         `json:"forks"`
		OpenIssues       int         `json:"open_issues"`
		Watchers         int         `json:"watchers"`
		DefaultBranch    string      `json:"default_branch"`
		Public           bool        `json:"public"`
	} `json:"forkee"`
	ProjectCard struct {
		URL        string `json:"url"`
		ProjectURL string `json:"project_url"`
		ColumnURL  string `json:"column_url"`
		ColumnID   int    `json:"column_id"`
		ID         int    `json:"id"`
		NodeID     string `json:"node_id"`
		Note       string `json:"note"`
		Archived   bool   `json:"archived"`
		Creator    struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"creator"`
		CreatedAt time.Time `json:"created_at"`
		UpdatedAt time.Time `json:"updated_at"`
	} `json:"project_card"`
	Member struct {
		Login             string `json:"login"`
		ID                int    `json:"id"`
		NodeID            string `json:"node_id"`
		AvatarURL         string `json:"avatar_url"`
		GravatarID        string `json:"gravatar_id"`
		URL               string `json:"url"`
		HTMLURL           string `json:"html_url"`
		FollowersURL      string `json:"followers_url"`
		FollowingURL      string `json:"following_url"`
		GistsURL          string `json:"gists_url"`
		StarredURL        string `json:"starred_url"`
		SubscriptionsURL  string `json:"subscriptions_url"`
		OrganizationsURL  string `json:"organizations_url"`
		ReposURL          string `json:"repos_url"`
		EventsURL         string `json:"events_url"`
		ReceivedEventsURL string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
	} `json:"member"`
	Sponsorship struct {
		NodeID      string    `json:"node_id"`
		CreatedAt   time.Time `json:"created_at"`
		Sponsorable struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"sponsorable"`
		Sponsor struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"sponsor"`
		PrivacyLevel string `json:"privacy_level"`
		Tier         struct {
			NodeID                string    `json:"node_id"`
			CreatedAt             time.Time `json:"created_at"`
			Description           string    `json:"description"`
			MonthlyPriceInCents   int       `json:"monthly_price_in_cents"`
			MonthlyPriceInDollars int       `json:"monthly_price_in_dollars"`
			Name                  string    `json:"name"`
			IsOneTime             bool      `json:"is_one_time"`
			IsCustomAmount        bool      `json:"is_custom_amount"`
		} `json:"tier"`
	} `json:"sponsorship"`
	Ref       string `json:"ref"`
	CommitOid string `json:"commit_oid"`
	Project   struct {
		OwnerURL   string `json:"owner_url"`
		URL        string `json:"url"`
		HTMLURL    string `json:"html_url"`
		ColumnsURL string `json:"columns_url"`
		ID         int    `json:"id"`
		NodeID     string `json:"node_id"`
		Name       string `json:"name"`
		Body       string `json:"body"`
		Number     int    `json:"number"`
		State      string `json:"state"`
		Creator    struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"creator"`
		CreatedAt time.Time `json:"created_at"`
		UpdatedAt time.Time `json:"updated_at"`
	} `json:"project"`
	Scope string `json:"scope"`
	Team  struct {
		Name            string `json:"name"`
		ID              int    `json:"id"`
		NodeID          string `json:"node_id"`
		Slug            string `json:"slug"`
		Description     string `json:"description"`
		Privacy         string `json:"privacy"`
		URL             string `json:"url"`
		HTMLURL         string `json:"html_url"`
		MembersURL      string `json:"members_url"`
		RepositoriesURL string `json:"repositories_url"`
		Permission      string `json:"permission"`
	} `json:"team"`
	Inputs struct {
		Name string `json:"name"`
	} `json:"inputs"`
	Workflow         string `json:"workflow"`
	SecurityAdvisory struct {
		GhsaID      string `json:"ghsa_id"`
		Summary     string `json:"summary"`
		Description string `json:"description"`
		Severity    string `json:"severity"`
		Identifiers []struct {
			Value string `json:"value"`
			Type  string `json:"type"`
		} `json:"identifiers"`
		References []struct {
			URL string `json:"url"`
		} `json:"references"`
		PublishedAt     time.Time   `json:"published_at"`
		UpdatedAt       time.Time   `json:"updated_at"`
		WithdrawnAt     interface{} `json:"withdrawn_at"`
		Vulnerabilities []struct {
			Package struct {
				Ecosystem string `json:"ecosystem"`
				Name      string `json:"name"`
			} `json:"package"`
			Severity               string `json:"severity"`
			VulnerableVersionRange string `json:"vulnerable_version_range"`
			FirstPatchedVersion    struct {
				Identifier string `json:"identifier"`
			} `json:"first_patched_version"`
		} `json:"vulnerabilities"`
	} `json:"security_advisory"`
	DeploymentStatus struct {
		URL     string `json:"url"`
		ID      int    `json:"id"`
		NodeID  string `json:"node_id"`
		State   string `json:"state"`
		Creator struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"creator"`
		Description   string    `json:"description"`
		Environment   string    `json:"environment"`
		TargetURL     string    `json:"target_url"`
		CreatedAt     time.Time `json:"created_at"`
		UpdatedAt     time.Time `json:"updated_at"`
		DeploymentURL string    `json:"deployment_url"`
		RepositoryURL string    `json:"repository_url"`
	} `json:"deployment_status"`
	Deployment struct {
		URL     string `json:"url"`
		ID      int    `json:"id"`
		NodeID  string `json:"node_id"`
		Sha     string `json:"sha"`
		Ref     string `json:"ref"`
		Task    string `json:"task"`
		Payload struct {
		} `json:"payload"`
		OriginalEnvironment string      `json:"original_environment"`
		Environment         string      `json:"environment"`
		Description         interface{} `json:"description"`
		Creator             struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"creator"`
		CreatedAt     time.Time `json:"created_at"`
		UpdatedAt     time.Time `json:"updated_at"`
		StatusesURL   string    `json:"statuses_url"`
		RepositoryURL string    `json:"repository_url"`
	} `json:"deployment"`
	Status      string `json:"status"`
	Number      int    `json:"number"`
	PullRequest struct {
		URL      string `json:"url"`
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		HTMLURL  string `json:"html_url"`
		DiffURL  string `json:"diff_url"`
		PatchURL string `json:"patch_url"`
		IssueURL string `json:"issue_url"`
		Number   int    `json:"number"`
		State    string `json:"state"`
		Locked   bool   `json:"locked"`
		Title    string `json:"title"`
		User     struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"user"`
		Body               string        `json:"body"`
		CreatedAt          time.Time     `json:"created_at"`
		UpdatedAt          time.Time     `json:"updated_at"`
		ClosedAt           interface{}   `json:"closed_at"`
		MergedAt           interface{}   `json:"merged_at"`
		MergeCommitSha     string        `json:"merge_commit_sha"`
		Assignee           interface{}   `json:"assignee"`
		Assignees          []interface{} `json:"assignees"`
		RequestedReviewers []interface{} `json:"requested_reviewers"`
		RequestedTeams     []interface{} `json:"requested_teams"`
		Labels             []interface{} `json:"labels"`
		Milestone          interface{}   `json:"milestone"`
		CommitsURL         string        `json:"commits_url"`
		ReviewCommentsURL  string        `json:"review_comments_url"`
		ReviewCommentURL   string        `json:"review_comment_url"`
		CommentsURL        string        `json:"comments_url"`
		StatusesURL        string        `json:"statuses_url"`
		Head               RefObject     `json:"head"`
		Base               RefObject     `json:"base"`
		Links              struct {
			Self struct {
				Href string `json:"href"`
			} `json:"self"`
			HTML struct {
				Href string `json:"href"`
			} `json:"html"`
			Issue struct {
				Href string `json:"href"`
			} `json:"issue"`
			Comments struct {
				Href string `json:"href"`
			} `json:"comments"`
			ReviewComments struct {
				Href string `json:"href"`
			} `json:"review_comments"`
			ReviewComment struct {
				Href string `json:"href"`
			} `json:"review_comment"`
			Commits struct {
				Href string `json:"href"`
			} `json:"commits"`
			Statuses struct {
				Href string `json:"href"`
			} `json:"statuses"`
		} `json:"_links"`
		AuthorAssociation   string      `json:"author_association"`
		Draft               bool        `json:"draft"`
		Merged              bool        `json:"merged"`
		Mergeable           interface{} `json:"mergeable"`
		Rebaseable          interface{} `json:"rebaseable"`
		MergeableState      string      `json:"mergeable_state"`
		MergedBy            interface{} `json:"merged_by"`
		Comments            int         `json:"comments"`
		ReviewComments      int         `json:"review_comments"`
		MaintainerCanModify bool        `json:"maintainer_can_modify"`
		Commits             int         `json:"commits"`
		Additions           int         `json:"additions"`
		Deletions           int         `json:"deletions"`
		ChangedFiles        int         `json:"changed_files"`
	} `json:"pull_request"`
	Review struct {
		ID     int    `json:"id"`
		NodeID string `json:"node_id"`
		User   struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"user"`
		Body              interface{} `json:"body"`
		CommitID          string      `json:"commit_id"`
		SubmittedAt       time.Time   `json:"submitted_at"`
		State             string      `json:"state"`
		HTMLURL           string      `json:"html_url"`
		PullRequestURL    string      `json:"pull_request_url"`
		AuthorAssociation string      `json:"author_association"`
		Links             struct {
			HTML struct {
				Href string `json:"href"`
			} `json:"html"`
			PullRequest struct {
				Href string `json:"href"`
			} `json:"pull_request"`
		} `json:"_links"`
	} `json:"review"`
	Package struct {
		ID          int       `json:"id"`
		Name        string    `json:"name"`
		PackageType string    `json:"package_type"`
		HTMLURL     string    `json:"html_url"`
		CreatedAt   time.Time `json:"created_at"`
		UpdatedAt   time.Time `json:"updated_at"`
		Owner       struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"owner"`
		PackageVersion struct {
			ID       int    `json:"id"`
			Version  string `json:"version"`
			Summary  string `json:"summary"`
			Body     string `json:"body"`
			BodyHTML string `json:"body_html"`
			Release  struct {
				URL             string `json:"url"`
				HTMLURL         string `json:"html_url"`
				ID              int    `json:"id"`
				TagName         string `json:"tag_name"`
				TargetCommitish string `json:"target_commitish"`
				Name            string `json:"name"`
				Draft           bool   `json:"draft"`
				Author          struct {
					Login             string `json:"login"`
					ID                int    `json:"id"`
					NodeID            string `json:"node_id"`
					AvatarURL         string `json:"avatar_url"`
					GravatarID        string `json:"gravatar_id"`
					URL               string `json:"url"`
					HTMLURL           string `json:"html_url"`
					FollowersURL      string `json:"followers_url"`
					FollowingURL      string `json:"following_url"`
					GistsURL          string `json:"gists_url"`
					StarredURL        string `json:"starred_url"`
					SubscriptionsURL  string `json:"subscriptions_url"`
					OrganizationsURL  string `json:"organizations_url"`
					ReposURL          string `json:"repos_url"`
					EventsURL         string `json:"events_url"`
					ReceivedEventsURL string `json:"received_events_url"`
					Type              string `json:"type"`
					SiteAdmin         bool   `json:"site_admin"`
				} `json:"author"`
				Prerelease  bool      `json:"prerelease"`
				CreatedAt   time.Time `json:"created_at"`
				PublishedAt time.Time `json:"published_at"`
			} `json:"release"`
			Manifest        string        `json:"manifest"`
			HTMLURL         string        `json:"html_url"`
			TagName         string        `json:"tag_name"`
			TargetCommitish string        `json:"target_commitish"`
			TargetOid       string        `json:"target_oid"`
			Draft           bool          `json:"draft"`
			Prerelease      bool          `json:"prerelease"`
			CreatedAt       time.Time     `json:"created_at"`
			UpdatedAt       time.Time     `json:"updated_at"`
			Metadata        []interface{} `json:"metadata"`
			PackageFiles    []struct {
				DownloadURL string    `json:"download_url"`
				ID          int       `json:"id"`
				Name        string    `json:"name"`
				Sha256      string    `json:"sha256"`
				Sha1        string    `json:"sha1"`
				Md5         string    `json:"md5"`
				ContentType string    `json:"content_type"`
				State       string    `json:"state"`
				Size        int       `json:"size"`
				CreatedAt   time.Time `json:"created_at"`
				UpdatedAt   time.Time `json:"updated_at"`
			} `json:"package_files"`
			Author struct {
				Login             string `json:"login"`
				ID                int    `json:"id"`
				NodeID            string `json:"node_id"`
				AvatarURL         string `json:"avatar_url"`
				GravatarID        string `json:"gravatar_id"`
				URL               string `json:"url"`
				HTMLURL           string `json:"html_url"`
				FollowersURL      string `json:"followers_url"`
				FollowingURL      string `json:"following_url"`
				GistsURL          string `json:"gists_url"`
				StarredURL        string `json:"starred_url"`
				SubscriptionsURL  string `json:"subscriptions_url"`
				OrganizationsURL  string `json:"organizations_url"`
				ReposURL          string `json:"repos_url"`
				EventsURL         string `json:"events_url"`
				ReceivedEventsURL string `json:"received_events_url"`
				Type              string `json:"type"`
				SiteAdmin         bool   `json:"site_admin"`
			} `json:"author"`
			InstallationCommand string `json:"installation_command"`
		} `json:"package_version"`
		Registry struct {
			AboutURL string `json:"about_url"`
			Name     string `json:"name"`
			Type     string `json:"type"`
			URL      string `json:"url"`
			Vendor   string `json:"vendor"`
		} `json:"registry"`
	} `json:"package"`
	EffectiveDate       time.Time `json:"effective_date"`
	MarketplacePurchase struct {
		Account struct {
			Type                     string `json:"type"`
			ID                       int    `json:"id"`
			NodeID                   string `json:"node_id"`
			Login                    string `json:"login"`
			OrganizationBillingEmail string `json:"organization_billing_email"`
		} `json:"account"`
		BillingCycle    string      `json:"billing_cycle"`
		UnitCount       int         `json:"unit_count"`
		OnFreeTrial     bool        `json:"on_free_trial"`
		FreeTrialEndsOn interface{} `json:"free_trial_ends_on"`
		NextBillingDate time.Time   `json:"next_billing_date"`
		Plan            struct {
			ID                  int      `json:"id"`
			Name                string   `json:"name"`
			Description         string   `json:"description"`
			MonthlyPriceInCents int      `json:"monthly_price_in_cents"`
			YearlyPriceInCents  int      `json:"yearly_price_in_cents"`
			PriceModel          string   `json:"price_model"`
			HasFreeTrial        bool     `json:"has_free_trial"`
			UnitName            string   `json:"unit_name"`
			Bullets             []string `json:"bullets"`
		} `json:"plan"`
	} `json:"marketplace_purchase"`
	Issue struct {
		URL           string `json:"url"`
		RepositoryURL string `json:"repository_url"`
		LabelsURL     string `json:"labels_url"`
		CommentsURL   string `json:"comments_url"`
		EventsURL     string `json:"events_url"`
		HTMLURL       string `json:"html_url"`
		ID            int    `json:"id"`
		NodeID        string `json:"node_id"`
		Number        int    `json:"number"`
		Title         string `json:"title"`
		User          struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"user"`
		Labels []struct {
			ID      int    `json:"id"`
			NodeID  string `json:"node_id"`
			URL     string `json:"url"`
			Name    string `json:"name"`
			Color   string `json:"color"`
			Default bool   `json:"default"`
		} `json:"labels"`
		State    string `json:"state"`
		Locked   bool   `json:"locked"`
		Assignee struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"assignee"`
		Assignees []struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"assignees"`
		Milestone struct {
			URL         string `json:"url"`
			HTMLURL     string `json:"html_url"`
			LabelsURL   string `json:"labels_url"`
			ID          int    `json:"id"`
			NodeID      string `json:"node_id"`
			Number      int    `json:"number"`
			Title       string `json:"title"`
			Description string `json:"description"`
			Creator     struct {
				Login             string `json:"login"`
				ID                int    `json:"id"`
				NodeID            string `json:"node_id"`
				AvatarURL         string `json:"avatar_url"`
				GravatarID        string `json:"gravatar_id"`
				URL               string `json:"url"`
				HTMLURL           string `json:"html_url"`
				FollowersURL      string `json:"followers_url"`
				FollowingURL      string `json:"following_url"`
				GistsURL          string `json:"gists_url"`
				StarredURL        string `json:"starred_url"`
				SubscriptionsURL  string `json:"subscriptions_url"`
				OrganizationsURL  string `json:"organizations_url"`
				ReposURL          string `json:"repos_url"`
				EventsURL         string `json:"events_url"`
				ReceivedEventsURL string `json:"received_events_url"`
				Type              string `json:"type"`
				SiteAdmin         bool   `json:"site_admin"`
			} `json:"creator"`
			OpenIssues   int       `json:"open_issues"`
			ClosedIssues int       `json:"closed_issues"`
			State        string    `json:"state"`
			CreatedAt    time.Time `json:"created_at"`
			UpdatedAt    time.Time `json:"updated_at"`
			DueOn        time.Time `json:"due_on"`
			ClosedAt     time.Time `json:"closed_at"`
		} `json:"milestone"`
		Comments          int         `json:"comments"`
		CreatedAt         time.Time   `json:"created_at"`
		UpdatedAt         time.Time   `json:"updated_at"`
		ClosedAt          interface{} `json:"closed_at"`
		AuthorAssociation string      `json:"author_association"`
		Body              string      `json:"body"`
	} `json:"issue"`
	Changes struct {
	} `json:"changes"`
	RefType       string      `json:"ref_type"`
	MasterBranch  string      `json:"master_branch"`
	Description   interface{} `json:"description"`
	PusherType    string      `json:"pusher_type"`
	Branch        string      `json:"branch"`
	ClientPayload struct {
		Unit        bool `json:"unit"`
		Integration bool `json:"integration"`
	} `json:"client_payload"`
	ID    int64 `json:"id"`
	Build struct {
		URL    string `json:"url"`
		Status string `json:"status"`
		Error  struct {
			Message interface{} `json:"message"`
		} `json:"error"`
		Pusher struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"pusher"`
		Commit    string    `json:"commit"`
		Duration  int       `json:"duration"`
		CreatedAt time.Time `json:"created_at"`
		UpdatedAt time.Time `json:"updated_at"`
	} `json:"build"`
	Before     string        `json:"before"`
	After      string        `json:"after"`
	Created    bool          `json:"created"`
	Deleted    bool          `json:"deleted"`
	Forced     bool          `json:"forced"`
	BaseRef    interface{}   `json:"base_ref"`
	Compare    string        `json:"compare"`
	Commits    []interface{} `json:"commits"`
	HeadCommit interface{}   `json:"head_commit"`
	Pusher     struct {
		Name  string `json:"name"`
		Email string `json:"email"`
	} `json:"pusher"`
	RepositorySelection string `json:"repository_selection"`
	RepositoriesAdded   []struct {
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		Name     string `json:"name"`
		FullName string `json:"full_name"`
		Private  bool   `json:"private"`
	} `json:"repositories_added"`
	RepositoriesRemoved []interface{} `json:"repositories_removed"`
	ContentReference    struct {
		ID        int    `json:"id"`
		NodeID    string `json:"node_id"`
		Reference string `json:"reference"`
	} `json:"content_reference"`
	Zen        string `json:"zen"`
	Membership struct {
		URL             string `json:"url"`
		State           string `json:"state"`
		Role            string `json:"role"`
		OrganizationURL string `json:"organization_url"`
		User            struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"user"`
	} `json:"membership"`
	Pages []struct {
		PageName string      `json:"page_name"`
		Title    string      `json:"title"`
		Summary  interface{} `json:"summary"`
		Action   string      `json:"action"`
		Sha      string      `json:"sha"`
		HTMLURL  string      `json:"html_url"`
	} `json:"pages"`
	Discussion struct {
		RepositoryURL string `json:"repository_url"`
		Category      struct {
			ID           int       `json:"id"`
			RepositoryID int       `json:"repository_id"`
			Emoji        string    `json:"emoji"`
			Name         string    `json:"name"`
			Description  string    `json:"description"`
			CreatedAt    time.Time `json:"created_at"`
			UpdatedAt    time.Time `json:"updated_at"`
			Slug         string    `json:"slug"`
			IsAnswerable bool      `json:"is_answerable"`
		} `json:"category"`
		AnswerHTMLURL  interface{} `json:"answer_html_url"`
		AnswerChosenAt interface{} `json:"answer_chosen_at"`
		AnswerChosenBy interface{} `json:"answer_chosen_by"`
		HTMLURL        string      `json:"html_url"`
		ID             int         `json:"id"`
		NodeID         string      `json:"node_id"`
		Number         int         `json:"number"`
		Title          string      `json:"title"`
		User           struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"user"`
		State             string      `json:"state"`
		Locked            bool        `json:"locked"`
		Comments          int         `json:"comments"`
		CreatedAt         time.Time   `json:"created_at"`
		UpdatedAt         time.Time   `json:"updated_at"`
		AuthorAssociation string      `json:"author_association"`
		ActiveLockReason  interface{} `json:"active_lock_reason"`
		Body              string      `json:"body"`
	} `json:"discussion"`
	Label struct {
		ID      int    `json:"id"`
		NodeID  string `json:"node_id"`
		URL     string `json:"url"`
		Name    string `json:"name"`
		Color   string `json:"color"`
		Default bool   `json:"default"`
	} `json:"label"`
	Release struct {
		URL             string      `json:"url"`
		AssetsURL       string      `json:"assets_url"`
		UploadURL       string      `json:"upload_url"`
		HTMLURL         string      `json:"html_url"`
		ID              int         `json:"id"`
		NodeID          string      `json:"node_id"`
		TagName         string      `json:"tag_name"`
		TargetCommitish string      `json:"target_commitish"`
		Name            interface{} `json:"name"`
		Draft           bool        `json:"draft"`
		Author          struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"author"`
		Prerelease  bool          `json:"prerelease"`
		CreatedAt   time.Time     `json:"created_at"`
		PublishedAt time.Time     `json:"published_at"`
		Assets      []interface{} `json:"assets"`
		TarballURL  string        `json:"tarball_url"`
		ZipballURL  string        `json:"zipball_url"`
		Body        interface{}   `json:"body"`
	} `json:"release"`
	Key struct {
		ID        int       `json:"id"`
		Key       string    `json:"key"`
		URL       string    `json:"url"`
		Title     string    `json:"title"`
		Verified  bool      `json:"verified"`
		CreatedAt time.Time `json:"created_at"`
		ReadOnly  bool      `json:"read_only"`
	} `json:"key"`
	Sha       string      `json:"sha"`
	Name      string      `json:"name"`
	TargetURL interface{} `json:"target_url"`
	Context   string      `json:"context"`
	State     string      `json:"state"`
	Commit    struct {
		Sha    string `json:"sha"`
		NodeID string `json:"node_id"`
		Commit struct {
			Author struct {
				Name  string    `json:"name"`
				Email string    `json:"email"`
				Date  time.Time `json:"date"`
			} `json:"author"`
			Committer struct {
				Name  string    `json:"name"`
				Email string    `json:"email"`
				Date  time.Time `json:"date"`
			} `json:"committer"`
			Message string `json:"message"`
			Tree    struct {
				Sha string `json:"sha"`
				URL string `json:"url"`
			} `json:"tree"`
			URL          string `json:"url"`
			CommentCount int    `json:"comment_count"`
			Verification struct {
				Verified  bool   `json:"verified"`
				Reason    string `json:"reason"`
				Signature string `json:"signature"`
				Payload   string `json:"payload"`
			} `json:"verification"`
		} `json:"commit"`
		URL         string `json:"url"`
		HTMLURL     string `json:"html_url"`
		CommentsURL string `json:"comments_url"`
		Author      struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"author"`
		Committer struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"committer"`
		Parents []interface{} `json:"parents"`
	} `json:"commit"`
	Branches []struct {
		Name   string `json:"name"`
		Commit struct {
			Sha string `json:"sha"`
			URL string `json:"url"`
		} `json:"commit"`
		Protected bool `json:"protected"`
	} `json:"branches"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	BlockedUser struct {
		Login             string `json:"login"`
		ID                int    `json:"id"`
		NodeID            string `json:"node_id"`
		AvatarURL         string `json:"avatar_url"`
		GravatarID        string `json:"gravatar_id"`
		URL               string `json:"url"`
		HTMLURL           string `json:"html_url"`
		FollowersURL      string `json:"followers_url"`
		FollowingURL      string `json:"following_url"`
		GistsURL          string `json:"gists_url"`
		StarredURL        string `json:"starred_url"`
		SubscriptionsURL  string `json:"subscriptions_url"`
		OrganizationsURL  string `json:"organizations_url"`
		ReposURL          string `json:"repos_url"`
		EventsURL         string `json:"events_url"`
		ReceivedEventsURL string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
	} `json:"blocked_user"`
	StarredAt time.Time `json:"starred_at"`
	Milestone struct {
		URL         string `json:"url"`
		HTMLURL     string `json:"html_url"`
		LabelsURL   string `json:"labels_url"`
		ID          int    `json:"id"`
		NodeID      string `json:"node_id"`
		Number      int    `json:"number"`
		Title       string `json:"title"`
		Description string `json:"description"`
		Creator     struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"creator"`
		OpenIssues   int         `json:"open_issues"`
		ClosedIssues int         `json:"closed_issues"`
		State        string      `json:"state"`
		CreatedAt    time.Time   `json:"created_at"`
		UpdatedAt    time.Time   `json:"updated_at"`
		DueOn        time.Time   `json:"due_on"`
		ClosedAt     interface{} `json:"closed_at"`
	} `json:"milestone"`
}

type App struct {
	ID     int    `json:"id"`
	NodeID string `json:"node_id"`
	Owner  struct {
		Login             string `json:"login"`
		ID                int    `json:"id"`
		NodeID            string `json:"node_id"`
		AvatarURL         string `json:"avatar_url"`
		GravatarID        string `json:"gravatar_id"`
		URL               string `json:"url"`
		HTMLURL           string `json:"html_url"`
		FollowersURL      string `json:"followers_url"`
		FollowingURL      string `json:"following_url"`
		GistsURL          string `json:"gists_url"`
		StarredURL        string `json:"starred_url"`
		SubscriptionsURL  string `json:"subscriptions_url"`
		OrganizationsURL  string `json:"organizations_url"`
		ReposURL          string `json:"repos_url"`
		EventsURL         string `json:"events_url"`
		ReceivedEventsURL string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
	} `json:"owner"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ExternalURL string    `json:"external_url"`
	HTMLURL     string    `json:"html_url"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Permissions struct {
		Administration             string `json:"administration"`
		Checks                     string `json:"checks"`
		Contents                   string `json:"contents"`
		Deployments                string `json:"deployments"`
		Issues                     string `json:"issues"`
		Members                    string `json:"members"`
		Metadata                   string `json:"metadata"`
		OrganizationAdministration string `json:"organization_administration"`
		OrganizationHooks          string `json:"organization_hooks"`
		OrganizationPlan           string `json:"organization_plan"`
		OrganizationProjects       string `json:"organization_projects"`
		OrganizationUserBlocking   string `json:"organization_user_blocking"`
		Pages                      string `json:"pages"`
		PullRequests               string `json:"pull_requests"`
		RepositoryHooks            string `json:"repository_hooks"`
		RepositoryProjects         string `json:"repository_projects"`
		Statuses                   string `json:"statuses"`
		TeamDiscussions            string `json:"team_discussions"`
		VulnerabilityAlerts        string `json:"vulnerability_alerts"`
	} `json:"permissions"`
	Events []interface{} `json:"events"`
}

type RefObject struct {
	Label string `json:"label"`
	Ref   string `json:"ref"`
	Sha   string `json:"sha"`
	User  struct {
		Login             string `json:"login"`
		ID                int    `json:"id"`
		NodeID            string `json:"node_id"`
		AvatarURL         string `json:"avatar_url"`
		GravatarID        string `json:"gravatar_id"`
		URL               string `json:"url"`
		HTMLURL           string `json:"html_url"`
		FollowersURL      string `json:"followers_url"`
		FollowingURL      string `json:"following_url"`
		GistsURL          string `json:"gists_url"`
		StarredURL        string `json:"starred_url"`
		SubscriptionsURL  string `json:"subscriptions_url"`
		OrganizationsURL  string `json:"organizations_url"`
		ReposURL          string `json:"repos_url"`
		EventsURL         string `json:"events_url"`
		ReceivedEventsURL string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
	} `json:"user"`
	Repo struct {
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		Name     string `json:"name"`
		FullName string `json:"full_name"`
		Private  bool   `json:"private"`
		Owner    struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"owner"`
		HTMLURL             string      `json:"html_url"`
		Description         interface{} `json:"description"`
		Fork                bool        `json:"fork"`
		URL                 string      `json:"url"`
		ForksURL            string      `json:"forks_url"`
		KeysURL             string      `json:"keys_url"`
		CollaboratorsURL    string      `json:"collaborators_url"`
		TeamsURL            string      `json:"teams_url"`
		HooksURL            string      `json:"hooks_url"`
		IssueEventsURL      string      `json:"issue_events_url"`
		EventsURL           string      `json:"events_url"`
		AssigneesURL        string      `json:"assignees_url"`
		BranchesURL         string      `json:"branches_url"`
		TagsURL             string      `json:"tags_url"`
		BlobsURL            string      `json:"blobs_url"`
		GitTagsURL          string      `json:"git_tags_url"`
		GitRefsURL          string      `json:"git_refs_url"`
		TreesURL            string      `json:"trees_url"`
		StatusesURL         string      `json:"statuses_url"`
		LanguagesURL        string      `json:"languages_url"`
		StargazersURL       string      `json:"stargazers_url"`
		ContributorsURL     string      `json:"contributors_url"`
		SubscribersURL      string      `json:"subscribers_url"`
		SubscriptionURL     string      `json:"subscription_url"`
		CommitsURL          string      `json:"commits_url"`
		GitCommitsURL       string      `json:"git_commits_url"`
		CommentsURL         string      `json:"comments_url"`
		IssueCommentURL     string      `json:"issue_comment_url"`
		ContentsURL         string      `json:"contents_url"`
		CompareURL          string      `json:"compare_url"`
		MergesURL           string      `json:"merges_url"`
		ArchiveURL          string      `json:"archive_url"`
		DownloadsURL        string      `json:"downloads_url"`
		IssuesURL           string      `json:"issues_url"`
		PullsURL            string      `json:"pulls_url"`
		MilestonesURL       string      `json:"milestones_url"`
		NotificationsURL    string      `json:"notifications_url"`
		LabelsURL           string      `json:"labels_url"`
		ReleasesURL         string      `json:"releases_url"`
		DeploymentsURL      string      `json:"deployments_url"`
		CreatedAt           time.Time   `json:"created_at"`
		UpdatedAt           time.Time   `json:"updated_at"`
		PushedAt            time.Time   `json:"pushed_at"`
		GitURL              string      `json:"git_url"`
		SSHURL              string      `json:"ssh_url"`
		CloneURL            string      `json:"clone_url"`
		SvnURL              string      `json:"svn_url"`
		Homepage            interface{} `json:"homepage"`
		Size                int         `json:"size"`
		StargazersCount     int         `json:"stargazers_count"`
		WatchersCount       int         `json:"watchers_count"`
		Language            string      `json:"language"`
		HasIssues           bool        `json:"has_issues"`
		HasProjects         bool        `json:"has_projects"`
		HasDownloads        bool        `json:"has_downloads"`
		HasWiki             bool        `json:"has_wiki"`
		HasPages            bool        `json:"has_pages"`
		ForksCount          int         `json:"forks_count"`
		MirrorURL           interface{} `json:"mirror_url"`
		Archived            bool        `json:"archived"`
		Disabled            bool        `json:"disabled"`
		OpenIssuesCount     int         `json:"open_issues_count"`
		License             interface{} `json:"license"`
		Forks               int         `json:"forks"`
		OpenIssues          int         `json:"open_issues"`
		Watchers            int         `json:"watchers"`
		DefaultBranch       string      `json:"default_branch"`
		AllowSquashMerge    bool        `json:"allow_squash_merge"`
		AllowMergeCommit    bool        `json:"allow_merge_commit"`
		AllowRebaseMerge    bool        `json:"allow_rebase_merge"`
		DeleteBranchOnMerge bool        `json:"delete_branch_on_merge"`
	} `json:"repo"`
}
